#!/bin/bash
source "$(dirname "${BASH_SOURCE}")/config.sh"

# Ajna Pedigree hook — fires on Stop event
# Captures decision lineage, artifacts, and session pedigree
# More thorough than session_log.sh: focuses on decision trail and reasoning provenance

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_ROOT" ]; then exit 0; fi

PEDIGREE_FILE="$REPO_ROOT/orchestration/state/DYN-PEDIGREE_LOG.md"
INTENTIONS_QUEUE="$REPO_ROOT/orchestration/state/DYN-INTENTIONS_QUEUE.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE=$(date '+%Y-%m-%d')
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
FINGERPRINT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Gather session artifacts
RECENT_COMMITS=$(git log --oneline -10 --since="6 hours ago" 2>/dev/null || echo "none")
COMMIT_COUNT=$(echo "$RECENT_COMMITS" | grep -c "." 2>/dev/null || echo "0")
FILES_MODIFIED=$(git diff --name-only HEAD~${COMMIT_COUNT}..HEAD 2>/dev/null | head -20 || echo "none")
STATE_FILES_TOUCHED=$(echo "$FILES_MODIFIED" | grep -E "state/|CLAUDE\.md|COCKPIT\.md" || echo "none")
CANON_FILES_TOUCHED=$(echo "$FILES_MODIFIED" | grep "canon/" || echo "none")
ENGINE_FILES_TOUCHED=$(echo "$FILES_MODIFIED" | grep "engine/" || echo "none")

# Count queued intentions (if any)
QUEUED_INTENTIONS="0"
if [ -f "$INTENTIONS_QUEUE" ]; then
    QUEUED_INTENTIONS=$(grep -c "^\- \*\*" "$INTENTIONS_QUEUE" 2>/dev/null || echo "0")
fi

# Create pedigree file with header if it doesn't exist
if [ ! -f "$PEDIGREE_FILE" ]; then
    cat > "$PEDIGREE_FILE" << 'HEADER'
# Ajna Pedigree Log
**Auto-generated by ajna_pedigree.sh hook**
**Purpose**: Decision lineage and session provenance tracking

---
HEADER
fi

# Append pedigree entry
cat >> "$PEDIGREE_FILE" << EOF

## Session: $TIMESTAMP
**Branch**: $BRANCH | **Fingerprint**: $FINGERPRINT | **Commits**: $COMMIT_COUNT

### Commits
\`\`\`
$RECENT_COMMITS
\`\`\`

### State Files Touched
\`\`\`
$STATE_FILES_TOUCHED
\`\`\`

### CANON Files Touched
\`\`\`
$CANON_FILES_TOUCHED
\`\`\`

### ENGINE Files Touched
\`\`\`
$ENGINE_FILES_TOUCHED
\`\`\`

### Queued Intentions
$QUEUED_INTENTIONS intention(s) captured by Intent Compass this session.

---
EOF

echo "[Hook] Ajna Pedigree logged to DYN-PEDIGREE_LOG.md ($COMMIT_COUNT commits, $QUEUED_INTENTIONS intentions queued)"
