#!/usr/bin/env bash
# constellation_watchdog.sh - Health monitor for Syncrescendence constellation
# Hardened liveness model: pane signal + heartbeat + artifact movement.

set -u

TMUX_SESSION="constellation"
TMUX_SOCKET="/private/tmp/tmux-$(id -u)/default"
TMUX_BIN="/opt/homebrew/bin/tmux -S ${TMUX_SOCKET}"
REPO_DIR="${SYNCRESCENDENCE_PATH:-$HOME/Desktop/syncrescendence}"
COCKPIT_SCRIPT="${REPO_DIR}/orchestration/scripts/cockpit.sh"
STATE_DIR="${REPO_DIR}/orchestration/state"
HEALTH_REPORT="${STATE_DIR}/DYN-CONSTELLATION_HEALTH.md"
HEARTBEAT_DIR="${STATE_DIR}/heartbeat"
WATCHDOG_STATE="${STATE_DIR}/.watchdog_state"
LOG_FILE="${HOME}/Library/Logs/syncrescendence-watchdog.log"

HEARTBEAT_WARN_S="${SYNCRESCENDENCE_HEARTBEAT_WARN_S:-300}"
HEARTBEAT_INTERRUPT_S="${SYNCRESCENDENCE_HEARTBEAT_INTERRUPT_S:-1800}"
MOVEMENT_WARN_S="${SYNCRESCENDENCE_MOVEMENT_WARN_S:-300}"
MOVEMENT_INTERRUPT_S="${SYNCRESCENDENCE_MOVEMENT_INTERRUPT_S:-1800}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "${LOG_FILE}" 2>/dev/null || true
}

write_alert() {
    local name="$1" detail="$2"
    local ts
    ts=$(date '+%Y%m%d%H%M')
    local alert_dir="${REPO_DIR}/-SOVEREIGN"
    mkdir -p "${alert_dir}" 2>/dev/null || true
    cat > "${alert_dir}/ALERT-${name}-${ts}.md" <<EOF_ALERT
# ALERT-${name}-${ts}

**Agent**: ${name}
**Timestamp**: $(date '+%Y-%m-%d %H:%M:%S')
**Detail**: ${detail}
**Status**: requires investigation
EOF_ALERT
}

attempt_recovery() {
    local uid_num
    uid_num="$(id -u)"
    local supervisor_plist="${HOME}/Library/LaunchAgents/com.syncrescendence.auto-ingest-supervisor.plist"
    local cockpit_wrapper="${REPO_DIR}/orchestration/scripts/launch_cockpit_when_docker_ready.sh"

    log "RECOVERY: attempting cockpit relaunch + auto-ingest supervisor kick"

    if [ -x "$cockpit_wrapper" ]; then
        /bin/bash "$cockpit_wrapper" >> "$LOG_FILE" 2>&1 || true
    else
        /bin/bash "$COCKPIT_SCRIPT" --launch-detached >> "$LOG_FILE" 2>&1 || true
    fi

    launchctl print "gui/${uid_num}/com.syncrescendence.auto-ingest-supervisor" >/dev/null 2>&1 || {
        [ -f "$supervisor_plist" ] && launchctl bootstrap "gui/${uid_num}" "$supervisor_plist" >/dev/null 2>&1 || true
    }
    launchctl kickstart -k "gui/${uid_num}/com.syncrescendence.auto-ingest-supervisor" >/dev/null 2>&1 || true
}

check_session() {
    if ! ${TMUX_BIN} has-session -t "${TMUX_SESSION}" 2>/dev/null; then
        log "CRITICAL: tmux session '${TMUX_SESSION}' not found"
        attempt_recovery
        sleep 3
        if ${TMUX_BIN} has-session -t "${TMUX_SESSION}" 2>/dev/null; then
            log "RECOVERY: tmux session restored"
            return 0
        fi

        cat > "${HEALTH_REPORT}" <<EOF_HEALTH
# Constellation Health
Last check: $(date '+%Y-%m-%d %H:%M:%S')

**CRITICAL**: tmux session '${TMUX_SESSION}' not found. Cockpit is DOWN.

---
*Generated by constellation_watchdog.sh*
EOF_HEALTH
        return 1
    fi
    return 0
}

capture_pane() {
    ${TMUX_BIN} capture-pane -t "${TMUX_SESSION}:${1}" -p -S -8 2>/dev/null || echo ""
}

analyze_pane() {
    local output="$1"

    if echo "$output" | grep -qiE "rate limit|usage limit|high demand|quota exceeded|Try again in"; then
        echo "RATE_LIMITED|API rate/usage limit"
        return
    fi

    if echo "$output" | grep -qiE "^ERROR|error:|fatal:|CRITICAL|panic"; then
        local err
        err=$(echo "$output" | grep -iE "error|fatal|panic" | head -1 | cut -c1-70)
        echo "ERROR|${err:-runtime error}"
        return
    fi

    if echo "$output" | grep -qiE "streaming|thinking|Explored|Processing|Analyzing|context left|Todo [0-9]"; then
        echo "ACTIVE|pane indicates execution"
        return
    fi

    if echo "$output" | grep -qE "^[>$#] |Type your message|Explain this"; then
        echo "IDLE|agent at prompt"
        return
    fi

    echo "IDLE|indeterminate pane state"
}

read_kv_value() {
    local file="$1"
    local key="$2"
    [ -f "$file" ] || { echo ""; return; }
    grep "^${key}=" "$file" 2>/dev/null | head -1 | cut -d'=' -f2-
}

heartbeat_age_for_agent() {
    local agent="$1"
    local hb_file="${HEARTBEAT_DIR}/${agent}.heartbeat"
    [ -f "$hb_file" ] || { echo 999999; return; }

    local ts
    ts=$(read_kv_value "$hb_file" "timestamp_unix")
    if [ -z "$ts" ]; then
        local m
        m=$(stat -f %m "$hb_file" 2>/dev/null || echo 0)
        echo $(( $(date +%s) - m ))
        return
    fi

    echo $(( $(date +%s) - ts ))
}

heartbeat_state_for_agent() {
    local agent="$1"
    local hb_file="${HEARTBEAT_DIR}/${agent}.heartbeat"
    local s
    s=$(read_kv_value "$hb_file" "state")
    [ -z "$s" ] && s="UNKNOWN"
    echo "$s"
}

artifact_age_for_agent() {
    local agent="$1"
    local latest=0
    local file

    for file in \
        "${REPO_DIR}/agents/${agent}/inbox/pending" \
        "${REPO_DIR}/agents/${agent}/inbox/active" \
        "${REPO_DIR}/agents/${agent}/inbox/done" \
        "${REPO_DIR}/agents/${agent}/inbox/failed" \
        "${REPO_DIR}/agents/${agent}/outbox" \
        "${REPO_DIR}/agents/${agent}/inbox/.current_task"; do
        if [ -e "$file" ]; then
            m=$(stat -f %m "$file" 2>/dev/null || echo 0)
            [ "$m" -gt "$latest" ] && latest="$m"
        fi
    done

    if [ "$latest" -eq 0 ]; then
        echo 999999
    else
        echo $(( $(date +%s) - latest ))
    fi
}

attempt_agent_recovery() {
    local name="$1"
    local pane="$2"
    local status="$3"
    local detail="$4"
    local hb_age="$5"
    local artifact_age="$6"

    case "$status" in
        STALE)
            # Interrupt only when both signals are stale long enough.
            if [ "$hb_age" -gt "$HEARTBEAT_INTERRUPT_S" ] && [ "$artifact_age" -gt "$MOVEMENT_INTERRUPT_S" ]; then
                ${TMUX_BIN} send-keys -t "${TMUX_SESSION}:${pane}" C-c C-c >/dev/null 2>&1 || true
                sleep 2
                ${TMUX_BIN} send-keys -t "${TMUX_SESSION}:${pane}" "" Enter >/dev/null 2>&1 || true
                log "RECOVERY: interrupt sent to ${name} (${pane}) — hb_age=${hb_age}s artifact_age=${artifact_age}s"
            elif [ "$hb_age" -gt "$HEARTBEAT_WARN_S" ] && [ "$artifact_age" -gt "$MOVEMENT_WARN_S" ]; then
                ${TMUX_BIN} send-keys -t "${TMUX_SESSION}:${pane}" "" Enter >/dev/null 2>&1 || true
                log "RECOVERY: heartbeat sent to ${name} (${pane}) — hb_age=${hb_age}s artifact_age=${artifact_age}s"
            fi
            ;;
        ERROR)
            log "RECOVERY: ERROR in ${name} (${pane}) — ${detail}"
            write_alert "$name" "$detail"
            ;;
        RATE_LIMITED)
            log "RECOVERY: RATE_LIMITED ${name} (${pane}) — ${detail}"
            ;;
    esac
}

compute_agent_status() {
    local pane_status="$1"
    local hb_age="$2"
    local artifact_age="$3"
    local hb_state="$4"

    case "$pane_status" in
        RATE_LIMITED|ERROR)
            echo "$pane_status"
            return
            ;;
        ACTIVE)
            echo "HEALTHY"
            return
            ;;
    esac

    if [ "$hb_age" -le "$HEARTBEAT_WARN_S" ] || [ "$artifact_age" -le "$MOVEMENT_WARN_S" ]; then
        echo "HEALTHY"
        return
    fi

    if [ "$hb_state" = "IN_PROGRESS" ] && [ "$hb_age" -le "$HEARTBEAT_INTERRUPT_S" ]; then
        echo "HEALTHY"
        return
    fi

    if [ "$hb_age" -gt "$HEARTBEAT_WARN_S" ] && [ "$artifact_age" -gt "$MOVEMENT_WARN_S" ]; then
        echo "STALE"
        return
    fi

    echo "IDLE"
}

persist_state_line() {
    local key="$1"
    local val="$2"
    echo "${key}|${val}" >> "$WATCHDOG_STATE.tmp"
}

main() {
    log "Health check starting"
    check_session || return 1

    : > "$WATCHDOG_STATE.tmp"

    {
        echo "# Constellation Health"
        echo "Last check: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "| Agent | Pane | Role | Status | Detail | HB Age(s) | Artifact Age(s) |"
        echo "|-------|------|------|--------|--------|-----------|------------------|"

        for entry in "psyche|1.1|CTO" "commander|1.3|COO" "adjudicator|1.5|CQO" "cartographer|1.7|CIO"; do
            IFS='|' read -r name pane role <<< "$entry"

            output=$(capture_pane "$pane")
            pane_result=$(analyze_pane "$output")
            pane_status=$(echo "$pane_result" | cut -d'|' -f1)
            pane_detail=$(echo "$pane_result" | cut -d'|' -f2-)

            hb_age=$(heartbeat_age_for_agent "$name")
            hb_state=$(heartbeat_state_for_agent "$name")
            art_age=$(artifact_age_for_agent "$name")

            status=$(compute_agent_status "$pane_status" "$hb_age" "$art_age" "$hb_state")
            detail="${pane_detail}; hb=${hb_state}"

            echo "| ${name} | ${pane} | ${role} | ${status} | ${detail} | ${hb_age} | ${art_age} |"

            log "${name} (${pane}): ${status} — ${detail} (hb=${hb_age}s artifact=${art_age}s)"
            attempt_agent_recovery "$name" "$pane" "$status" "$detail" "$hb_age" "$art_age"

            persist_state_line "$name" "${status};${hb_age};${art_age}"
        done

        bridge_status="DOWN"
        if ssh -o BatchMode=yes -o ConnectTimeout=5 macbook-air hostname >/dev/null 2>&1; then
            bridge_status="HEALTHY"
        fi
        echo ""
        echo "## Neural Bridge (MBA ↔ Mac mini)"
        echo "| Direction | Status |"
        echo "|-----------|--------|"
        echo "| Mac mini → MBA | ${bridge_status} |"
        log "Neural Bridge: ${bridge_status}"

        echo ""
        echo "---"
        echo "*Generated by constellation_watchdog.sh at $(date '+%Y-%m-%d %H:%M:%S')*"
    } > "${HEALTH_REPORT}"

    mv "$WATCHDOG_STATE.tmp" "$WATCHDOG_STATE"
    log "Health check complete"

    if ! docker info >/dev/null 2>&1; then
        log "CRITICAL: Docker is DOWN"
        if command -v open >/dev/null 2>&1; then
            open -a Docker >/dev/null 2>&1 || true
            sleep 5
        fi
        if docker info >/dev/null 2>&1; then
            log "RECOVERY: Docker restarted"
        else
            log "RECOVERY: Docker restart attempt failed"
        fi
    fi
}

main "$@"
