#!/bin/bash
# Session log hook — fires on Stop event
# Captures: timestamp, branch, recent commits, files changed
# Appends to orchestration/state/DYN-SESSION_LOG.md

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_ROOT" ]; then exit 0; fi

LOG_FILE="$REPO_ROOT/orchestration/state/DYN-SESSION_LOG.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "none")
FILES_CHANGED=$(git diff --stat HEAD~1 2>/dev/null | tail -1 || echo "unknown")

# Create file with header if it doesn't exist
if [ ! -f "$LOG_FILE" ]; then
    cat > "$LOG_FILE" << 'HEADER'
# Session Log
**Auto-generated by session_log.sh hook**

---
HEADER
fi

# Append session entry
cat >> "$LOG_FILE" << EOF

### $TIMESTAMP | Branch: $BRANCH
**Recent commits**:
\`\`\`
$RECENT_COMMITS
\`\`\`
**Changes**: $FILES_CHANGED

---
EOF

echo "[Hook] Session logged to DYN-SESSION_LOG.md"
