name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install jinja2 pyyaml

      # -- Core verification (adapted from make verify) --
      - name: Structure verification
        run: |
          echo "=== Structure Verification ==="
          echo -n "Unexpected subdirectories: "
          find . -mindepth 2 -type d -name "scaffolding" 2>/dev/null | wc -l
          echo -n "Root .md files: "
          ls *.md 2>/dev/null | wc -l || echo "0"

      - name: Ledger verification
        run: |
          echo "=== Ledger Verification ==="
          echo -n "DYN-TASKS.csv rows: "
          wc -l < 00-ORCHESTRATION/state/DYN-TASKS.csv
          echo -n "DYN-PROJECTS.csv rows: "
          wc -l < 00-ORCHESTRATION/state/DYN-PROJECTS.csv

      - name: Content verification
        run: |
          echo "=== Content Verification ==="
          echo -n "Processed sources: "
          ls 04-SOURCES/processed/*.md 2>/dev/null | wc -l || echo "0"
          echo -n "CANON with integrations: "
          grep -rl "SOURCE-" 01-CANON/*.md 2>/dev/null | wc -l || echo "0"

      - name: Git status
        run: git status --short

      # -- Python script validation --
      - name: Validate Python scripts parse correctly
        run: |
          echo "=== Python Syntax Check ==="
          FAILED=0
          for f in 00-ORCHESTRATION/scripts/*.py; do
            if ! python -m py_compile "$f"; then
              echo "FAIL: $f"
              FAILED=1
            else
              echo "OK: $f"
            fi
          done
          exit $FAILED

      # -- Sensitive file check --
      - name: Check for .env and .db files
        run: |
          echo "=== Sensitive File Check ==="
          FOUND=0
          ENV_FILES=$(find . -name "*.env" -o -name ".env" -o -name ".env.*" | grep -v '.github' || true)
          DB_FILES=$(find . -name "*.db" | grep -v '.github' || true)
          if [ -n "$ENV_FILES" ]; then
            echo "ERROR: .env files found in repo:"
            echo "$ENV_FILES"
            FOUND=1
          fi
          if [ -n "$DB_FILES" ]; then
            echo "ERROR: .db files found in repo:"
            echo "$DB_FILES"
            FOUND=1
          fi
          if [ "$FOUND" -eq 0 ]; then
            echo "OK: No .env or .db files found"
          fi
          exit $FOUND

      # -- CSV column consistency --
      - name: Validate CSV column counts
        run: |
          echo "=== CSV Validation ==="
          FAILED=0
          for csv in 00-ORCHESTRATION/state/DYN-TASKS.csv 00-ORCHESTRATION/state/DYN-PROJECTS.csv; do
            if [ ! -f "$csv" ]; then
              echo "WARN: $csv not found, skipping"
              continue
            fi
            HEADER_COLS=$(head -1 "$csv" | awk -F',' '{print NF}')
            echo "$csv: header has $HEADER_COLS columns"
            LINE=1
            while IFS= read -r row; do
              LINE=$((LINE + 1))
              ROW_COLS=$(echo "$row" | awk -F',' '{print NF}')
              if [ "$ROW_COLS" -ne "$HEADER_COLS" ]; then
                echo "ERROR: $csv line $LINE has $ROW_COLS columns (expected $HEADER_COLS)"
                FAILED=1
              fi
            done < <(tail -n +2 "$csv")
          done
          if [ "$FAILED" -eq 0 ]; then
            echo "OK: All CSV files have consistent column counts"
          fi
          exit $FAILED
