name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyyaml

      # -- Validate YAML files --
      - name: Validate YAML files
        run: |
          echo "=== YAML Validation ==="
          FAILED=0
          for f in $(find . -name "*.yaml" -o -name "*.yml" | grep -v '.github/' | sort); do
            if python -c "import yaml; yaml.safe_load(open('$f'))" 2>/dev/null; then
              echo "OK: $f"
            else
              echo "FAIL: $f"
              FAILED=1
            fi
          done
          exit $FAILED

      # -- Check broken wikilinks --
      - name: Check for broken wikilinks
        run: |
          echo "=== Wikilink Check ==="
          BROKEN=0

          # Build index of all markdown filenames (without path, without extension)
          FILENAMES=$(find . -name "*.md" | sed 's|.*/||; s|\.md$||' | sort -u)

          # Extract all [[...]] references from markdown files
          for md in $(find . -name "*.md" -not -path './.github/*'); do
            # Extract wikilink targets: [[Target]] or [[Target|Display]]
            LINKS=$(grep -oP '\[\[([^\]|]+)' "$md" | sed 's/\[\[//' | sort -u || true)
            for link in $LINKS; do
              # Skip links that look like URLs or anchors
              if echo "$link" | grep -qE '^https?://|^#'; then
                continue
              fi
              # Check if target file exists (by filename match)
              if ! echo "$FILENAMES" | grep -qxF "$link"; then
                echo "BROKEN: $md -> [[$link]]"
                BROKEN=$((BROKEN + 1))
              fi
            done
          done

          if [ "$BROKEN" -eq 0 ]; then
            echo "OK: No broken wikilinks found"
          else
            echo ""
            echo "Found $BROKEN broken wikilink(s)"
            echo "Note: Some may be intentional forward-references. Review above."
            # Warn but don't fail -- broken wikilinks may be intentional placeholders
            exit 0
          fi
