#!/usr/bin/env python3
"""Validate successor-shell constitutional surfaces and core projections."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
STATE_DIR = REPO_ROOT / "orchestration" / "state"
JSON_OUT = STATE_DIR / "CONSTITUTION-VALIDATION-REPORT.json"
MD_OUT = STATE_DIR / "CONSTITUTION-VALIDATION-REPORT.md"

ALLOWED_ROOT = {
    ".claude",
    ".gemini",
    ".obsidian",
    ".gitattributes",
    ".github",
    ".gitignore",
    "AGENTS.md",
    "BOOT.md",
    "CLAUDE.md",
    "CONTINUOUS-IMPROVEMENT.md",
    "GEMINI.md",
    "INTER-OFFICE.md",
    "Makefile",
    "README.md",
    "communications",
    "executive",
    "knowledge",
    "memory",
    "offices",
    "operators",
    "orchestration",
    "pedigree",
    "playbooks",
    "program",
    "runtime",
    "validated-patterns",
    "WORK-LOOP.md",
}

TRANSITIONAL_ROOT = {
    "finalize_cowork_relay_job.py",
}

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "BOOT.md",
    "WORK-LOOP.md",
    "INTER-OFFICE.md",
    "CONTINUOUS-IMPROVEMENT.md",
    "CLAUDE.md",
    "GEMINI.md",
    "playbooks/oracle/PLAYBOOK.md",
    "playbooks/commander/PLAYBOOK.md",
    "playbooks/cartographer/PLAYBOOK.md",
    "playbooks/manus/PLAYBOOK.md",
    "playbooks/google-ai-studio/PLAYBOOK.md",
    "playbooks/notebooklm/PLAYBOOK.md",
    "playbooks/opencode/PLAYBOOK.md",
    "playbooks/openhands/PLAYBOOK.md",
    "playbooks/aider/PLAYBOOK.md",
    "offices/commander/README.md",
    "offices/adjudicator/README.md",
    "offices/cartographer/README.md",
    "offices/ajna/README.md",
    "offices/psyche/README.md",
    "orchestration/state/impl/DISSERTATION-SYNCRESCENDENCE-v1.md",
    "orchestration/state/impl/DISSERTATION-CH02-INSTITUTIONAL-ARCHITECTURE-v1.md",
    "orchestration/state/impl/DISSERTATION-CH03-BUILT-REALITY-v1.md",
    "orchestration/state/impl/EXOCORTEX-TELEOLOGY-REGISTRY-CC90.md",
    "orchestration/state/impl/EXOCORTEX-CONTROL-PLANE-CC91.md",
]

ADAPTER_REQUIREMENTS = {
    "CLAUDE.md": [
        "AGENTS.md",
        "BOOT.md",
        "WORK-LOOP.md",
        "INTER-OFFICE.md",
        "CONTINUOUS-IMPROVEMENT.md",
    ],
    "GEMINI.md": [
        "AGENTS.md",
        "BOOT.md",
        "WORK-LOOP.md",
        "INTER-OFFICE.md",
        "CONTINUOUS-IMPROVEMENT.md",
    ],
}

FEDERAL_OFFICES = [
    "Commander",
    "Adjudicator",
    "Ajna",
    "Cartographer",
    "Psyche",
]


@dataclass
class Finding:
    level: str
    path: str
    note: str


def gather_findings() -> list[Finding]:
    findings: list[Finding] = []
    root_entries = {path.name for path in REPO_ROOT.iterdir() if path.name not in {".git", ".DS_Store"}}

    for name in sorted(root_entries - ALLOWED_ROOT - TRANSITIONAL_ROOT):
        findings.append(Finding("error", name, "unexpected root entry outside successor-shell allowlist"))

    for name in sorted(root_entries & TRANSITIONAL_ROOT):
        findings.append(Finding("warning", name, "transitional root operator remains pending internalization"))

    for rel in REQUIRED_PATHS:
        if not (REPO_ROOT / rel).exists():
            findings.append(Finding("error", rel, "required constitutional or projection surface missing"))

    agents_text = (REPO_ROOT / "AGENTS.md").read_text(encoding="utf-8")
    for office in FEDERAL_OFFICES:
        if office not in agents_text:
            findings.append(Finding("error", "AGENTS.md", f"missing federal office declaration for {office}"))

    for rel, required_tokens in ADAPTER_REQUIREMENTS.items():
        text = (REPO_ROOT / rel).read_text(encoding="utf-8")
        for token in required_tokens:
            if token not in text:
                findings.append(Finding("error", rel, f"missing constitutional deferral anchor {token}"))

    for rel in (
        "CLAUDE.md",
        "GEMINI.md",
    ):
        text = (REPO_ROOT / rel).read_text(encoding="utf-8")
        if "generated by operators/config/render_successor_adapters.py" not in text:
            findings.append(Finding("warning", rel, "adapter veneer is not under successor-shell render discipline"))

    return findings


def render_markdown(findings: list[Finding]) -> str:
    errors = [item for item in findings if item.level == "error"]
    warnings = [item for item in findings if item.level == "warning"]
    lines = [
        "# Constitution Validation Report",
        "",
        f"- errors: {len(errors)}",
        f"- warnings: {len(warnings)}",
        "",
    ]
    for title, items in (("Errors", errors), ("Warnings", warnings)):
        lines.append(f"## {title}")
        lines.append("")
        if not items:
            lines.append("- none")
            lines.append("")
            continue
        for item in items:
            lines.append(f"- `{item.path}`: {item.note}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict-warnings", action="store_true")
    args = parser.parse_args()

    findings = gather_findings()
    JSON_OUT.write_text(
        json.dumps([asdict(item) for item in findings], indent=2) + "\n",
        encoding="utf-8",
    )
    MD_OUT.write_text(render_markdown(findings), encoding="utf-8")

    errors = [item for item in findings if item.level == "error"]
    warnings = [item for item in findings if item.level == "warning"]

    if errors:
        for item in errors:
            print(f"ERROR: {item.path}: {item.note}")
        return 1
    if warnings and args.strict_warnings:
        for item in warnings:
            print(f"WARNING: {item.path}: {item.note}")
        return 1

    print(f"Constitution validation passed with {len(warnings)} warning(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
