#!/usr/bin/env bash
# constellation_watchdog.sh - Health monitor for Syncrescendence constellation
# Monitors all agent panes, detects failures, writes structured health report
# IMPL-Q-0030 | INT-1804
#
# Run manually: bash constellation_watchdog.sh
# Run via launchd: see 00-ORCHESTRATION/launchd/com.syncrescendence.watchdog.plist

# NOTE: No set -e/-o pipefail — monitoring scripts must degrade gracefully,
# never crash on grep mismatches or transient tmux errors (Adjudicator pattern)
set -u

TMUX_SESSION="constellation"
# Explicit socket path — launchd can't reliably resolve TMUX_TMPDIR
TMUX_SOCKET="/private/tmp/tmux-$(id -u)/default"
TMUX_BIN="/opt/homebrew/bin/tmux -S ${TMUX_SOCKET}"
REPO_DIR="${HOME}/Desktop/syncrescendence"
COCKPIT_SCRIPT="${REPO_DIR}/00-ORCHESTRATION/scripts/cockpit.sh"
STATE_DIR="${REPO_DIR}/00-ORCHESTRATION/state"
HEALTH_REPORT="${STATE_DIR}/DYN-CONSTELLATION_HEALTH.md"
WATCHDOG_STATE="${STATE_DIR}/.watchdog_state"
LOG_FILE="${HOME}/Library/Logs/syncrescendence-watchdog.log"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
UNIX_TIME=$(date +%s)

log() {
    echo "[${TIMESTAMP}] $*" >> "${LOG_FILE}" 2>/dev/null || true
}

write_alert() {
    local name="$1" detail="$2"
    local ts
    ts=$(date '+%Y%m%d%H%M')
    local alert_dir="${REPO_DIR}/-SOVEREIGN"
    mkdir -p "${alert_dir}" 2>/dev/null || true
    cat > "${alert_dir}/ALERT-${name}-${ts}.md" <<EOF
# ALERT-${name}-${ts}

**Agent**: ${name}
**Timestamp**: $(date '+%Y-%m-%d %H:%M:%S')
**Detail**: ${detail}
**Status**: requires investigation
EOF
}

attempt_agent_recovery() {
    local name="$1" pane="$2" status="$3"
    local elapsed="${RECOVERY_ELAPSED:-}"
    local detail="${RECOVERY_DETAIL:-}"

    case "$status" in
        STALE)
            if [ -n "$elapsed" ] && [ "$elapsed" -gt 1800 ]; then
                ${TMUX_BIN} send-keys -t "${TMUX_SESSION}:${pane}" C-c C-c >/dev/null 2>&1 || true
                sleep 3
                ${TMUX_BIN} send-keys -t "${TMUX_SESSION}:${pane}" "" Enter >/dev/null 2>&1 || true
                log "RECOVERY: Sent interrupt to ${name} (${pane}) — stale ${elapsed}s"
                log "RECOVERY: Sent heartbeat to ${name} (${pane}) — stale ${elapsed}s"
            elif [ -n "$elapsed" ] && [ "$elapsed" -gt 300 ]; then
                ${TMUX_BIN} send-keys -t "${TMUX_SESSION}:${pane}" "" Enter >/dev/null 2>&1 || true
                log "RECOVERY: Sent heartbeat to ${name} (${pane}) — stale ${elapsed}s"
            fi
            ;;
        ERROR)
            log "RECOVERY: ERROR in ${name} (${pane}) — ${detail} — requires investigation"
            write_alert "$name" "$detail"
            ;;
        RATE_LIMITED)
            log "RECOVERY: RATE_LIMITED ${name} (${pane}) — ${detail}"
            if [ -n "$elapsed" ] && [ "$elapsed" -gt 3600 ]; then
                write_alert "$name" "${detail} (>${elapsed}s)"
            fi
            ;;
    esac
}

attempt_recovery() {
    local uid_num
    uid_num="$(id -u)"
    local supervisor_plist="${HOME}/Library/LaunchAgents/com.syncrescendence.auto-ingest-supervisor.plist"
    local cockpit_wrapper="${REPO_DIR}/00-ORCHESTRATION/scripts/launch_cockpit_when_docker_ready.sh"

    log "RECOVERY: attempting cockpit relaunch + auto-ingest supervisor kick"

    # Relaunch cockpit with Docker readiness guard.
    if [ -x "$cockpit_wrapper" ]; then
        /bin/bash "$cockpit_wrapper" >> "$LOG_FILE" 2>&1 || true
    else
        /bin/bash "$COCKPIT_SCRIPT" --launch-detached >> "$LOG_FILE" 2>&1 || true
    fi

    # Ensure supervisor label is loaded and kicked.
    launchctl print "gui/${uid_num}/com.syncrescendence.auto-ingest-supervisor" >/dev/null 2>&1 || {
        [ -f "$supervisor_plist" ] && launchctl bootstrap "gui/${uid_num}" "$supervisor_plist" >/dev/null 2>&1 || true
    }
    launchctl kickstart -k "gui/${uid_num}/com.syncrescendence.auto-ingest-supervisor" >/dev/null 2>&1 || true
}

check_session() {
    if ! ${TMUX_BIN} has-session -t "${TMUX_SESSION}" 2>/dev/null; then
        log "CRITICAL: tmux session '${TMUX_SESSION}' not found"
        attempt_recovery
        sleep 3
        if ${TMUX_BIN} has-session -t "${TMUX_SESSION}" 2>/dev/null; then
            log "RECOVERY: tmux session '${TMUX_SESSION}' restored"
            return 0
        fi

        cat > "${HEALTH_REPORT}" <<EOF
# Constellation Health
Last check: ${TIMESTAMP}

**CRITICAL**: tmux session '${TMUX_SESSION}' not found. Cockpit is DOWN.

---
*Generated by constellation_watchdog.sh*
EOF
        return 1
    fi
    return 0
}

capture_pane() {
    # Timeout prevents launchd hanging on tmux IPC deadlocks
    ${TMUX_BIN} capture-pane -t "${TMUX_SESSION}:${1}" -p -S -5 2>/dev/null || echo ""
}

hash_output() {
    printf '%s' "$1" | md5 2>/dev/null || printf '%s' "$1" | md5sum 2>/dev/null | cut -d' ' -f1
}

load_prev() {
    local agent="$1"
    [ -f "${WATCHDOG_STATE}" ] && grep "^${agent}|" "${WATCHDOG_STATE}" 2>/dev/null || echo ""
}

analyze() {
    local output="$1" prev_hash="$2" prev_time="$3"
    local current_hash
    current_hash=$(hash_output "$output")

    if echo "$output" | grep -qiE "rate limit|usage limit|high demand|quota exceeded|Try again in"; then
        local detail="API rate/usage limit"
        if [ -n "$prev_time" ] && [ "$current_hash" = "$prev_hash" ]; then
            local elapsed=$(( UNIX_TIME - prev_time ))
            [ "$elapsed" -gt 900 ] && detail="${detail} (>${elapsed}s — WARNING)"
        fi
        echo "RATE_LIMITED|${detail}|${current_hash}"; return
    fi

    if echo "$output" | grep -qE "^ERROR|error:|fatal:|CRITICAL|panic"; then
        local err; err=$(echo "$output" | grep -iE "error|fatal|panic" | head -1 | cut -c1-50)
        echo "ERROR|${err}|${current_hash}"; return
    fi

    if echo "$output" | grep -qE "streaming|thinking|Explored|Processing|Analyzing|context left|Todo [0-9]"; then
        local ind; ind=$(echo "$output" | grep -oE "(streaming [0-9ms]+|thinking|Explored|[0-9]+% context left|Todo [0-9]+/[0-9]+)" | tail -1)
        echo "HEALTHY|${ind:-active}|${current_hash}"; return
    fi

    if [ -n "$prev_hash" ] && [ "$current_hash" = "$prev_hash" ] && [ -n "$prev_time" ]; then
        local elapsed=$(( UNIX_TIME - prev_time ))
        [ "$elapsed" -gt 300 ] && { echo "STALE|no change for ${elapsed}s — WARNING|${current_hash}"; return; }
    fi

    if echo "$output" | grep -qE "^[>$#] |Type your message|Explain this"; then
        echo "IDLE|at prompt|${current_hash}"; return
    fi

    echo "IDLE|indeterminate|${current_hash}"
}

main() {
    log "Health check starting"
    check_session || return 1

    local new_state=""

    {
        echo "# Constellation Health"
        echo "Last check: ${TIMESTAMP}"
        echo ""
        echo "| Agent | Pane | Role | Status | Detail |"
        echo "|-------|------|------|--------|--------|"

        for entry in "Psyche|1.1|CTO" "Commander|1.3|COO" "Adjudicator|1.5|CQO" "Cartographer|1.7|CIO"; do
            IFS='|' read -r name pane role <<< "$entry"
            local output; output=$(capture_pane "$pane")

            local prev_line; prev_line=$(load_prev "$name")
            local prev_hash="" prev_time=""
            if [ -n "$prev_line" ]; then
                prev_hash=$(echo "$prev_line" | cut -d'|' -f2)
                prev_time=$(echo "$prev_line" | cut -d'|' -f3)
            fi

            local result; result=$(analyze "$output" "$prev_hash" "$prev_time")
            local status detail current_hash
            status=$(echo "$result" | cut -d'|' -f1)
            detail=$(echo "$result" | cut -d'|' -f2)
            current_hash=$(echo "$result" | cut -d'|' -f3)

            local state_time="$UNIX_TIME"
            [ "$current_hash" = "$prev_hash" ] && [ -n "$prev_time" ] && state_time="$prev_time"

            echo "| ${name} | ${pane} | ${role} | ${status} | ${detail} |"
            new_state="${new_state}${name}|${current_hash}|${state_time}"$'\n'

            log "${name} (${pane}): ${status} — ${detail}"

            local elapsed=""
            if [ -n "$prev_time" ]; then
                elapsed=$(( UNIX_TIME - prev_time ))
            fi
            RECOVERY_ELAPSED="$elapsed"
            RECOVERY_DETAIL="$detail"
            attempt_agent_recovery "$name" "$pane" "$status"
        done

        # Neural Bridge health check (MBA connectivity)
        local bridge_status="DOWN"
        if ssh -o BatchMode=yes -o ConnectTimeout=5 macbook-air hostname >/dev/null 2>&1; then
            bridge_status="HEALTHY"
        fi
        echo ""
        echo "## Neural Bridge (MBA ↔ Mac mini)"
        echo "| Direction | Status |"
        echo "|-----------|--------|"
        echo "| Mac mini → MBA | ${bridge_status} |"
        log "Neural Bridge: ${bridge_status}"

        echo ""
        echo "---"
        echo "*Generated by constellation_watchdog.sh at ${TIMESTAMP}*"
    } > "${HEALTH_REPORT}"

    printf '%s' "$new_state" > "${WATCHDOG_STATE}"
    log "Health check complete"

    # Docker health check
    if ! docker info >/dev/null 2>&1; then
        log "CRITICAL: Docker is DOWN"
        if command -v open >/dev/null 2>&1; then
            open -a Docker >/dev/null 2>&1 || true
            sleep 5
        fi
        if docker info >/dev/null 2>&1; then
            log "RECOVERY: Docker restarted"
        else
            log "RECOVERY: Docker restart attempt failed"
        fi
    fi
}

main "$@"
