#!/usr/bin/env bash
# constellation_watchdog.sh - Health monitor for Syncrescendence constellation
# Monitors all agent panes, detects failures, writes structured health report
# IMPL-Q-0030 | INT-1804
#
# Run manually: bash constellation_watchdog.sh
# Run via launchd: see 00-ORCHESTRATION/launchd/com.syncrescendence.watchdog.plist

# NOTE: No set -e/-o pipefail — monitoring scripts must degrade gracefully,
# never crash on grep mismatches or transient tmux errors (Adjudicator pattern)
set -u

TMUX_SESSION="constellation"
# Explicit socket path — launchd can't reliably resolve TMUX_TMPDIR
TMUX_SOCKET="/private/tmp/tmux-$(id -u)/default"
TMUX_BIN="/opt/homebrew/bin/tmux -S ${TMUX_SOCKET}"
REPO_DIR="${HOME}/Desktop/syncrescendence"
STATE_DIR="${REPO_DIR}/00-ORCHESTRATION/state"
HEALTH_REPORT="${STATE_DIR}/DYN-CONSTELLATION_HEALTH.md"
WATCHDOG_STATE="${STATE_DIR}/.watchdog_state"
LOG_FILE="${HOME}/Library/Logs/syncrescendence-watchdog.log"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
UNIX_TIME=$(date +%s)

log() {
    echo "[${TIMESTAMP}] $*" >> "${LOG_FILE}" 2>/dev/null || true
}

check_session() {
    if ! ${TMUX_BIN} has-session -t "${TMUX_SESSION}" 2>/dev/null; then
        log "CRITICAL: tmux session '${TMUX_SESSION}' not found"
        cat > "${HEALTH_REPORT}" <<EOF
# Constellation Health
Last check: ${TIMESTAMP}

**CRITICAL**: tmux session '${TMUX_SESSION}' not found. Cockpit is DOWN.

---
*Generated by constellation_watchdog.sh*
EOF
        return 1
    fi
    return 0
}

capture_pane() {
    # Timeout prevents launchd hanging on tmux IPC deadlocks
    ${TMUX_BIN} capture-pane -t "${TMUX_SESSION}:${1}" -p -S -5 2>/dev/null || echo ""
}

hash_output() {
    printf '%s' "$1" | md5 2>/dev/null || printf '%s' "$1" | md5sum 2>/dev/null | cut -d' ' -f1
}

load_prev() {
    local agent="$1"
    [ -f "${WATCHDOG_STATE}" ] && grep "^${agent}|" "${WATCHDOG_STATE}" 2>/dev/null || echo ""
}

analyze() {
    local output="$1" prev_hash="$2" prev_time="$3"
    local current_hash
    current_hash=$(hash_output "$output")

    if echo "$output" | grep -qiE "rate limit|usage limit|high demand|quota exceeded|Try again in"; then
        local detail="API rate/usage limit"
        if [ -n "$prev_time" ] && [ "$current_hash" = "$prev_hash" ]; then
            local elapsed=$(( UNIX_TIME - prev_time ))
            [ "$elapsed" -gt 900 ] && detail="${detail} (>${elapsed}s — WARNING)"
        fi
        echo "RATE_LIMITED|${detail}|${current_hash}"; return
    fi

    if echo "$output" | grep -qE "^ERROR|error:|fatal:|CRITICAL|panic"; then
        local err; err=$(echo "$output" | grep -iE "error|fatal|panic" | head -1 | cut -c1-50)
        echo "ERROR|${err}|${current_hash}"; return
    fi

    if echo "$output" | grep -qE "streaming|thinking|Explored|Processing|Analyzing|context left|Todo [0-9]"; then
        local ind; ind=$(echo "$output" | grep -oE "(streaming [0-9ms]+|thinking|Explored|[0-9]+% context left|Todo [0-9]+/[0-9]+)" | tail -1)
        echo "HEALTHY|${ind:-active}|${current_hash}"; return
    fi

    if [ -n "$prev_hash" ] && [ "$current_hash" = "$prev_hash" ] && [ -n "$prev_time" ]; then
        local elapsed=$(( UNIX_TIME - prev_time ))
        [ "$elapsed" -gt 300 ] && { echo "STALE|no change for ${elapsed}s — WARNING|${current_hash}"; return; }
    fi

    if echo "$output" | grep -qE "^[>$#] |Type your message|Explain this"; then
        echo "IDLE|at prompt|${current_hash}"; return
    fi

    echo "IDLE|indeterminate|${current_hash}"
}

main() {
    log "Health check starting"
    check_session || return 1

    local new_state=""

    {
        echo "# Constellation Health"
        echo "Last check: ${TIMESTAMP}"
        echo ""
        echo "| Agent | Pane | Role | Status | Detail |"
        echo "|-------|------|------|--------|--------|"

        for entry in "Psyche|1.1|CTO" "Commander|1.3|COO" "Adjudicator|1.5|CQO" "Cartographer|1.7|CIO"; do
            IFS='|' read -r name pane role <<< "$entry"
            local output; output=$(capture_pane "$pane")

            local prev_line; prev_line=$(load_prev "$name")
            local prev_hash="" prev_time=""
            if [ -n "$prev_line" ]; then
                prev_hash=$(echo "$prev_line" | cut -d'|' -f2)
                prev_time=$(echo "$prev_line" | cut -d'|' -f3)
            fi

            local result; result=$(analyze "$output" "$prev_hash" "$prev_time")
            local status detail current_hash
            status=$(echo "$result" | cut -d'|' -f1)
            detail=$(echo "$result" | cut -d'|' -f2)
            current_hash=$(echo "$result" | cut -d'|' -f3)

            local state_time="$UNIX_TIME"
            [ "$current_hash" = "$prev_hash" ] && [ -n "$prev_time" ] && state_time="$prev_time"

            echo "| ${name} | ${pane} | ${role} | ${status} | ${detail} |"
            new_state="${new_state}${name}|${current_hash}|${state_time}"$'\n'

            log "${name} (${pane}): ${status} — ${detail}"
        done

        echo ""
        echo "---"
        echo "*Generated by constellation_watchdog.sh at ${TIMESTAMP}*"
    } > "${HEALTH_REPORT}"

    printf '%s' "$new_state" > "${WATCHDOG_STATE}"
    log "Health check complete"
}

main "$@"
